# Generated by Django 5.2.17 on 2026-09-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='external_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='track',
            name='external_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
