# Generated by Django 5.2.17 on 2026-09-28 11:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('projects', '0001_initial'),
        ('voting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(condition=models.Q(('voting_token__isnull', False)), fields=('voting_token',), name='unique_vote_per_token_total'),
        ),
    ]
